# Generated by Django 2.2.6 on 2019-10-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191012_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='context',
        ),
    ]
