# Generated by Django 2.2.6 on 2019-10-13 04:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='context',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
