# Generated by Django 2.2.6 on 2019-10-13 06:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
