# Generated by Django 2.2.6 on 2019-10-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191013_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNumber',
        ),
    ]
